name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Subir archivos vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_38403121
          password: 9L9D6JafjCw
          local-dir: ./
          server-dir: /htdocs/

    # - name: Run test suite
    #   run: composer run-script test
